%%{init: {"gitGraph": {"rotateCommitLabel": false, "showBranches": true},
          "themeVariables": {"commitLabelFontSize": "13px"}}}%%
gitGraph
  commit id: "the bug"
  branch feature-2
  commit id: "first try"
  commit id: "green"
  commit id: "checked"
  checkout main
  merge feature-2 tag: "merged"
