%%{init: {"gitGraph": {"rotateCommitLabel": false, "showBranches": true},
          "themeVariables": {"commitLabelFontSize": "13px"}}}%%
gitGraph
  commit id: "bug 002"
  branch feature-2-categories
  commit id: "logic"
  commit id: "seed"
  commit id: "form"
  checkout main
  merge feature-2-categories tag: "merged"
